### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by mrved3** [DhyanMoradiya/Bwind#1]
Hello I need a database acess for Reference

**Comment by DhyanMoradiya** [comment]
It'ss over firebase and I can't share firebase credentials

**Comment by mrved3** [comment]
Sir I'm developing flutter application for college from the google
developer student club. This is the vast project of the study app. In this
project all the study material for students we provide in this app i need
your app as a reference but i cant access the firebase authentication. I
kindly request you help me to develop the application.
